### ISSUE TITLE
just a message + tool suggestion

### ISSUE THREAD

**Issue by micoro** [imawizard/MiguruWM#1]
Hi, this is not an actual issue, but I didn't now hot to leave a message here (you can close/delete it).

I am very interested in a TWM that actually works and has all the basic function i need. I tried all the TWM that you linked but most tend to crash easily, lose windows, are abandoned or lack some basic features.
Amethyst and komorebi are currently the best. Tried amethyst (and still trying to use it) but has some small problems + crashes that make it not a solid tool to use (also kinda abandoned). Maybe I will test komorebi again in the future but I preferred to use windows virtual desktop for robustness and because of the tool I am linking below: it is amazing to manage your desktops when you have many windows open.

Since you are going to use the windows virtual desktop feature you too may be interested in this: https://github.com/newlooper/VirtualSpace.

When you have a working version I will try it. Good luck!

**Comment by imawizard** [comment]
Thanks for the tool suggestion, I added a link to the readme.

What about Workspacer or GlazeWM? I can't recall whether they use native virtual desktops, but together with komorebi und Amethyst Windows they're the most popular ones and maintained.

**Comment by micoro** [comment]
I tried to use glazeWM for few days (before i started to use VirtualSpace).

The problem I had with glazeWM were:
* There was no "tiled" layout. I like to have the master area on the left with just one window and the secondary area on the right with the windows that stacks vertically. GlazeWM tiles tall by default and you have to manually give a command (everytime) to have the layout that I like as default. If I have to do things manually then FancyZones is easier to use and more stable.
* It crashed on me many times until I gave up. 
* GlazeWM has its own virtual desktop implementation but now that I use VirtualSpace I will hardly renounce it. Having the possibility to see what I have open and on which desktop is really useful when you have a lot of window open.


I tried workspacer but just briefly and I don't remember the exact reason I discarded it.


EDIT: read the new readme.
~~I see that currently you have not implemented the "tiled" layout I described above. Is it planned or is it our of scope for you?
Personally I think It is the best as default: half of the screen is dedicated to the window you are currently working on. The other half (the secondary zone) can contain the other windows you are currently interested in but can accept to be smaller. Other layouts (like tall) can be useful but each new window open will shrink the main window making it harder to work on it.~~

BTW I am on linux now, later I will try to use the tool.

EDIT2: just tried it on windows. Seems to work well! Will give more feedback later. Also the "tall" layout is exactly what I wanted. In other tools "tall" means all windows horizontally stacked.

**Comment by imawizard** [comment]
The layouts 'tall' and 'wide' refer to the behaviour described here: [Getting started with xmonad](https://xmonad.org/tour.html)

Like you said, you have a master pane and a secondary one, the limit of windows that go into the master pane is increased/decreased with RAlt+comma/period (0 = unlimited, resulting in [rows/columns](https://xmonad.org/images/tour/inc2.png))
