### ISSUE TITLE
differentiate lateral padding from vertical padding

### ISSUE THREAD

**Issue by micoro** [imawizard/MiguruWM#7]
Hi,
would it make sense to differentiate vertical padding from lateral?

I have recently bought a wide screen monitor. Now when I have only one window or when I use the monocle layout I have one REAAAALLY wide window and sometimes it can be unwelcome and not easy to use.
So I was thinking about setting a monocle layout with big lateral padding to have a more manageable window.

________________________________________________________

Are you still working on this project? I have been using this for months now and I really like it. 
It still lack a couple of feature that are mandatory to make it actually usable: 

1. a way to ignore window/programs so that they are not managed (#3)
2. a way to ignore window that requires administrator privileges

Without these features the tool gets in the way so many times that is as helpful as it is hurtful (at least for the programs I use).
I have implemented both in my local version but with a junky_approach_that_kinda_works_because_I_know_how_I_made_it.

I hope you are still working on it. Nice work.

**Comment by imawizard** [comment]
Hi Michele,

for your use-case you it'd make sense to specify horizontal/vertical padding, but also one pair of paddings for when there's only one window in any tiling layout, and another pair for when there are multiple tiled windows, wouldn't it?

So e.g. when you only have one master, the horizontal padding is 20 and the vertical is 5, however, when a second window gets tiled, the padding switches to 10 in horizontal and 5 in vertical padding. What do you think?

As for the two other points, could you test the newest commit to see if it's working as one would expect it?

**Comment by imawizard** [comment]
Hey micoro,

can you try out the latest version and see whether it's now more helpful than hurtful? :D
`padding` now has the fields `left`, `top`, `right` and `bottom`.

**Comment by imawizard** [comment]
@micoro: I'll close this issue due to inactivity.
